language: node_js
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
env:
  global:
    secure: "TC5+gq/qaDwc537/FNMpDvvOUxbSiJaGPMh/18u+I4fg5sJnfavWJtNlzXH4W/9ACRAtDDFpxcfVZtqHeb3q+Nh1WE8Sd1Wmlmo/FZoDj7rUw3oMJIpSt1Yjns3N+A+T0YjrIVF7/aGgh+7eNuho9YW8PwrM5CgqGsjruRA7U24="
    secure: "TC5+gq/qaDwc537/FNMpDvvOUxbSiJaGPMh/18u+I4fg5sJnfavWJtNlzXH4W/9ACRAtDDFpxcfVZtqHeb3q+Nh1WE8Sd1Wmlmo/FZoDj7rUw3oMJIpSt1Yjns3N+A+T0YjrIVF7/aGgh+7eNuho9YW8PwrM5CgqGsjruRA7U24="